name: 'GitHub Action for git commit'
description: 'Commits any changed files and pushes the result back to origin branch.'
author: 'elstudio'
branding:
  icon: 'git-commit'
  color: 'green'
inputs: 
  wdPath:
    description: 'Working directory path'
    required: false
  pushBranch:
    description: 'Override branch to push to'
    requried: false
  debug:
    description: 'Print script debugging info'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'entrypoint.sh'
  # env:
  #   wd_path: ${{ inputs.wdPath }}
  #   push_branch: ${{ inputs.pushBranch }}
  #   debug: ${{ inputs.debug }}
